name: Build and Release

on:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download wasi-sdk
        run: |
          curl -LO https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-25/wasi-sdk-25.0-x86_64-linux.tar.gz
          tar -xzf wasi-sdk-25.0-x86_64-linux.tar.gz
          echo "WASI_SDK_PATH=$PWD/wasi-sdk-25.0-x86_64-linux" >> $GITHUB_ENV

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Build with Makefile
        run: make

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
